env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

plugins: ['react']

settings:
  react:
    version: '16'
